name: Git Action Issue

on:
  issues:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: run build
        run: node packages/issues-to-data/dist/index.js
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
